package by.bsuir.kaziukovich.oop.datalayer.readerwriter.bookinfo.impl;

import by.bsuir.kaziukovich.oop.datalayer.info.book.BookInfo;
import by.bsuir.kaziukovich.oop.datalayer.info.book.BookType;
import by.bsuir.kaziukovich.oop.datalayer.info.book.impl.LibraryBookInfo;
import by.bsuir.kaziukovich.oop.datalayer.readerwriter.InfoReadWriteException;
import by.bsuir.kaziukovich.oop.datalayer.readerwriter.bookinfo.BookInfoReaderWriter;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Class implementing InfoReaderWriter interface for BookInfo type, reading info from file
 */
public class LibraryBookInfoFileReaderWriter implements BookInfoReaderWriter {
    /**
     * Pattern to check input string
     */
    private final Pattern bookInfoPattern;

    /**
     * Group name of book author for regex
     */
    private final String authorGroupName;

    /**
     * Group name of book title for regex
     */
    private final String titleGroupName;

    /**
     * Group name of book type for regex
     */
    private final String bookTypeGroupName;

    /**
     * Group name of book ISBN for regex
     */
    private final String isbnGroupName;

    /**
     * Delimiter of line entries
     */
    private final char delimiter;

    /**
     * Reads lines from specified path
     * @param path Specified path
     * @return Set of BookInfo's generated by read lines
     * @throws InfoReadWriteException In case of file read error
     */
    @Override
    public List<BookInfo> readFrom(String path) throws InfoReadWriteException {
        List<BookInfo> result = new ArrayList<>();
        List<String> lines;
        Matcher bookPatternMatcher;

        if (path == null) {
            throw new IllegalArgumentException("Path shouldn't be null");
        }

        try {
            lines = Files.readAllLines(Paths.get(path));
        } catch (IOException ioException) {
            throw new InfoReadWriteException("Error reading file " + path, ioException);
        }

        for (String line : lines) {
            bookPatternMatcher = bookInfoPattern.matcher(line);
            if (bookPatternMatcher.matches()) {
                try {
                    result.add(new LibraryBookInfo(bookPatternMatcher.group(titleGroupName),
                            bookPatternMatcher.group(authorGroupName), bookPatternMatcher.group(isbnGroupName),
                            BookType.valueOf(bookPatternMatcher.group(bookTypeGroupName))));
                } catch (IllegalArgumentException ignored) { }
            }
        }
        return result;
    }

    /**
     * Writes strings to specified path generated by specified list
     * @param infoList Set of values to be written
     * @param path Specified path
     * @throws InfoReadWriteException In case of file write error
     */
    @Override
    public void writeTo(List<BookInfo> infoList, String path) throws InfoReadWriteException {
        List<String> bookLines = new ArrayList<>();

        if ((infoList == null) || (path == null)) {
            throw new IllegalArgumentException("Arguments shouldn't be null");
        }

        for (BookInfo bookInfo : infoList) {
            bookLines.add(bookInfo.getAuthor() + delimiter + bookInfo.getTitle() + delimiter + bookInfo.getIsbn()
                    + delimiter + bookInfo.getBookType().toString());
        }

        try {
            Files.write(Paths.get(path), bookLines);
        } catch (IOException ioException) {
            throw new InfoReadWriteException("Error writing to file " + path, ioException);
        }
    }

    /**
     * Checks if current object equals to given
     * @param o Object to check equality to
     * @return True if objects are equal, otherwise false
     */
    @Override
    public boolean equals(Object o) {
        LibraryBookInfoFileReaderWriter libraryBookInfoFileReaderWriter;

        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        libraryBookInfoFileReaderWriter = (LibraryBookInfoFileReaderWriter) o;
        return delimiter == libraryBookInfoFileReaderWriter.delimiter &&
                Objects.equals(bookInfoPattern, libraryBookInfoFileReaderWriter.bookInfoPattern) &&
                Objects.equals(authorGroupName, libraryBookInfoFileReaderWriter.authorGroupName) &&
                Objects.equals(titleGroupName, libraryBookInfoFileReaderWriter.titleGroupName) &&
                Objects.equals(bookTypeGroupName, libraryBookInfoFileReaderWriter.bookTypeGroupName) &&
                Objects.equals(isbnGroupName, libraryBookInfoFileReaderWriter.isbnGroupName);
    }

    /**
     * Generates hash of current object
     * @return Hash of current object
     */
    @Override
    public int hashCode() {
        return Objects.hash(bookInfoPattern, authorGroupName, titleGroupName, bookTypeGroupName, isbnGroupName,
                delimiter);
    }

    /**
     * Generates string representation of object
     * @return String representation of object
     */
    @Override
    public String toString() {
        return getClass().getName() + "@bookInfoPattern: " + bookInfoPattern.toString() + ", authorGroupName: "
                + authorGroupName + ", titleGroupName: " + titleGroupName + ", bookTypeGroupName: "
                + bookTypeGroupName + ", isbnGroupName: " + isbnGroupName + ", delimiter: " + delimiter;
    }

    /**
     * Constructor for ReaderWriter instance
     */
    public LibraryBookInfoFileReaderWriter() {
        authorGroupName = "author";
        titleGroupName = "title";
        bookTypeGroupName = "type";
        isbnGroupName = "isbn";
        delimiter = ':';
        bookInfoPattern = Pattern.compile("^(?<" + authorGroupName + ">[a-zA-Z]+[a-zA-Z\\s]*)"
                + delimiter + "(?<" + titleGroupName + ">[a-zA-Z]+[a-zA-Z\\s]*)"  + delimiter + "(?<" + isbnGroupName
                + ">[\\d\\-X]{10,})" + delimiter + "(?<" + bookTypeGroupName + ">\\w+)$");
    }
}
